import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  contentContainer: { padding: 20, paddingBottom: 40 },
  heroCard: { borderWidth: 1, borderRadius: 18, paddingHorizontal: 18, paddingVertical: 18, gap: 10, marginBottom: 2, shadowOpacity: 0.16, shadowOffset: { width: 0, height: 8 }, shadowRadius: 14, elevation: 6 },
  heroIconWrap: { width: 54, height: 54, borderRadius: 16, alignItems: 'center', justifyContent: 'center', borderWidth: 1, alignSelf: 'center' },
  heroTitle: { fontSize: 24, fontWeight: '800', textAlign: 'center' },
  heroSubtitle: { fontSize: 14, lineHeight: 20, textAlign: 'center' },
  heroBadge: { alignSelf: 'center', flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 999, borderWidth: 1 },
  heroBadgeText: { fontSize: 12, fontWeight: '700', letterSpacing: 0.3 },
  inputSection: { marginBottom: 2 },
  typeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 2 },
  typeCard: { borderWidth: 1, borderRadius: 16, padding: 12, marginTop: 8, width: '100%', alignSelf: 'center', shadowOpacity: 0.12, shadowOffset: { width: 0, height: 6 }, shadowRadius: 12, elevation: 5 },
  typeChip: { paddingVertical: 10, paddingHorizontal: 14, borderRadius: 16, borderWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 10, minWidth: '48%' },
  typeChipActive: { backgroundColor: '#2f9e44', borderColor: '#2f9e44' },
  typeIconWrap: { width: 34, height: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  typeIconWrapActive: { backgroundColor: 'rgba(255,255,255,0.15)', borderColor: 'rgba(255,255,255,0.45)' },
  typeChipText: { fontSize: 13, fontWeight: '600' },
  inputWrapper: { position: 'relative' },
  input: { borderWidth: 1.5, borderRadius: 12, paddingHorizontal: 16, paddingVertical: 12, paddingRight: 44, fontSize: 16, minHeight: 44 },
  fieldLabel: { fontSize: 13, fontWeight: '600' },
  fieldInput: { borderWidth: 1.5, borderRadius: 12, paddingHorizontal: 16, paddingVertical: 12, fontSize: 16 },
  segmented: { flexDirection: 'row', gap: 8, marginTop: 6, marginBottom: 6 },
  segBtn: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1 },
  segBtnActive: { backgroundColor: '#2f9e44', borderColor: '#2f9e44' },
  segText: { fontSize: 13, fontWeight: '600' },
  toggleRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 8 },
  clearButton: { position: 'absolute', right: 12, top: 8, width: 32, height: 32, borderRadius: 16, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  charCount: { fontSize: 12, marginTop: 6, textAlign: 'right' },
  generateRow: { marginTop: 10, alignItems: 'stretch' },
  generateBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, paddingVertical: 16, borderRadius: 12, backgroundColor: '#2f9e44', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 4, elevation: 3 },
  generateText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  errorContainer: { flexDirection: 'row', alignItems: 'center', padding: 12, borderRadius: 8, gap: 8, marginBottom: 16 },
  errorText: { flex: 1, fontSize: 14, fontWeight: '500' },
  loadingContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 40, gap: 12 },
  loadingText: { fontSize: 14, fontWeight: '500' },
  qrSection: { alignItems: 'center', gap: 20, marginVertical: 20 },
  qrContainer: { padding: 12, width: '90%', maxWidth: 380, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  qrWrap: { borderRadius: 8, overflow: 'hidden' },
  actionButtons: { flexDirection: 'row', gap: 12, width: '100%' },
  actionButton: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 14, paddingHorizontal: 20, borderRadius: 12, borderWidth: 1.5, borderColor: '#4a9eff' },
  actionButtonText: { fontSize: 15, fontWeight: '600' },
  placeholder: { alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderStyle: 'dashed', borderRadius: 16, padding: 40, gap: 16, marginVertical: 20 },
  placeholderIcon: { width: 120, height: 120, borderRadius: 60, alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  placeholderTitle: { fontSize: 18, fontWeight: '700' },
  placeholderText: { fontSize: 14, textAlign: 'center', lineHeight: 20 },
  infoTitle: { fontSize: 14, fontWeight: '700', marginBottom: 4 },
  infoText: { fontSize: 13, lineHeight: 18 },
  customSection: { borderWidth: 1, borderRadius: 18, padding: 16, marginTop: 12, gap: 18 },
  customHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  customTitle: { fontSize: 17, fontWeight: '700' },
  customSubtitle: { fontSize: 13, marginTop: 4 },
  customBadge: { flexDirection: 'row', alignItems: 'center', paddingVertical: 6, paddingHorizontal: 10, borderWidth: 1, borderRadius: 20, gap: 6 },
  customBadgeText: { fontSize: 12, fontWeight: '700' },
  customModesRow: { flexGrow: 1, gap: 12, paddingVertical: 1 },
  customModeChip: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 14, borderWidth: 1 },
  customModeChipActive: { backgroundColor: '#2563eb', borderColor: '#2563eb', shadowColor: '#2563eb', shadowOpacity: 0.27, shadowOffset: { width: 0, height: 6 }, shadowRadius: 10, elevation: 6 },
  customModeText: { fontSize: 13, fontWeight: '600' },
  logoCard: { flexDirection: 'row', gap: 16, borderWidth: 1, borderRadius: 16, padding: 12 },
  logoPreview: { width: 96, height: 96, borderRadius: 14, overflow: 'hidden', borderWidth: 1 },
  logoImage: { width: '100%', height: '100%' },
  logoPlaceholder: { flex: 1, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderRadius: 14, padding: 8 },
  logoActionBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: 12, paddingVertical: 12 },
  logoActionText: { color: '#fff', fontWeight: '700' },
  logoActionBtnSecondary: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 10, borderRadius: 12, borderWidth: 1 },
  logoActionTextSecondary: { fontWeight: '600' },
  frameCard: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10 },
  frameLabelTitle: { fontSize: 14, fontWeight: '700' },
  frameInput: { borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, fontSize: 15 },
  frameCounter: { textAlign: 'right', fontSize: 12 },
  customHint: { fontSize: 12, fontWeight: '600', textAlign: 'center' },
  qrPreview: { width: '100%', alignItems: 'center', gap: 12, paddingBottom: 6 },
  qrPreviewFramed: { paddingHorizontal: 8, paddingTop: 8 },
  qrWrapElevated: { borderRadius: 12, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.2, shadowRadius: 10, elevation: 8, backgroundColor: '#fff' },
  frameLabelBlock: { width: '90%', borderRadius: 12, paddingVertical: 12, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, shadowColor: '#000', shadowOpacity: 0.28, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 8 },
  frameLabelText: { color: '#fff', fontWeight: '700', letterSpacing: 1.1, fontSize: 14, textShadowColor: 'rgba(0,0,0,0.35)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 3 },
  logoOverlay: { position: 'absolute', width: 68, height: 68, borderRadius: 16, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', top: '50%', left: '50%', marginLeft: -34, marginTop: -34, elevation: 9, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: 6, borderWidth: 2, borderColor: '#e2e8f0', overflow: 'hidden' },
  logoOverlayImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  colorButton: { marginTop: 10, flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 10, paddingHorizontal: 14, borderRadius: 12 },
  colorButtonText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  colorModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', alignItems: 'center', justifyContent: 'center', padding: 20 },
  colorModalCard: { width: '100%', maxWidth: 380, borderWidth: 1, borderRadius: 16, padding: 16, gap: 12 },
  colorModalTitle: { fontSize: 16, fontWeight: '800' },
  colorSwatchGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 6 },
  colorSwatch: { width: 44, height: 44, borderRadius: 12, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  colorSwatchActive: { shadowColor: '#2563eb', shadowOpacity: 0.4, shadowRadius: 6, shadowOffset: { width: 0, height: 3 }, elevation: 4 },
  colorModalActions: { flexDirection: 'row', gap: 10, marginTop: 9 },
  colorBtn: { flex: 1, paddingVertical: 12, borderRadius: 12, alignItems: 'center' },
  colorBtnText: { fontSize: 14, fontWeight: '700' },
  rewardOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', alignItems: 'center', justifyContent: 'center', padding: 20 },
  rewardCard: { width: '100%', borderWidth: 1, borderRadius: 16, padding: 16, gap: 12 },
  rewardHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  rewardTitle: { fontSize: 18, fontWeight: '700' },
  rewardSubtitle: { fontSize: 13 },
  rewardCta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 14, borderRadius: 12, gap: 8 },
  rewardCtaText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  premiumBtn: { borderRadius: 12 },
  premiumText: { fontSize: 15 }
});
